### PR TITLE
Always set default content type if body is set.

### PR DESCRIPTION
**Pull request by frodsan**
Related to this: https://github.com/soveran/cuba/issues/69

### CODE REVIEW

**Comment by soveran** [comment]
:thumbsup:

**Comment by frodsan** [comment]
Is `seg` stable for 1.0.0?

**Comment by soveran** [comment]
Absolutely! I just released seg 1.0.0.

**Comment by frodsan** [comment]
Perfect!

**Comment by soveran** [comment]
Released as 2.1.2.

**Pull request merged**
